### ISSUE TITLE
community-weighted growth rate

### ISSUE THREAD

**Issue by chenyj8** [jlw-ecoevo/gRodon#3]
Hi,

Does gRodon underestimate the weighted community-level growth rate when it is larger than 5 hours?

**Comment by jlw-ecoevo** [comment]
In general, any of gRodon's modes will tend to underestimate minimal doubling times when they are longer than 5 hours. This is likely true of any codon-usage based predictor of max growth rate. So, to answer your question, yes. Unfortunately, not much we can do about it. That being said, gRodon should reliably at least be able to tell you that the doubling time is >5 hours.

**Comment by chenyj8** [comment]
Hi,

Thanks for the reply. 

I have a question about calculating the community-level growth rate. To calculate it, a list of all genes (from prodigal) and a list of ribosomal protein genes (from gene annotation) are required. However, the genes obtained from metagenomic sample might be associated with prokaryotes, eukaryotes, virus, etc. Since gRodon focuses on prokaryotes, maybe I should first remove genes that are not associated with prokaryotes?

**Comment by jlw-ecoevo** [comment]
Yes, gRodon was trained on prokaryotes so if your have many genes (particularly ribosomal proteins) from euks or viruses that could mess with your prediction somewhat. We are working on a version of the software to deal with this automatically (and incorporate euks into the predictions), but for now you could try any software that predicts whether a contig comes from euks or viruses and filter those out of your assemblies if you are worried about your samples having large euk or viral populations.

**Comment by chenyj8** [comment]
That's interesting. Not sure how you will annotate the ribosomal protein genes automatically. I use KEGG annotation and I use a list of KEGG orthologies (KOs) that are associated with bacterial/archaeal ribosomal proteins. Please see the list here: https://www.genome.jp/brite/ko03011

**Comment by jlw-ecoevo** [comment]
I'd likely choose to do it at the contig level using, e.g., https://github.com/patrickwest/EukRep and https://github.com/jiarong/VirSorter2, that ways works for both ribosomal and non-ribosomal genes

**Comment by chenyj8** [comment]
Could you please clarify? Doesn't gRodon require a list of protein-coding genes and a list of ribosomal protein genes?

**Comment by jlw-ecoevo** [comment]
Yes - but you should know which contigs those genes are located on from your prodigal output (or whichever gene prediction tool you used), so if you know which contigs are, for example, eukaryotic, you will also know which genes are eukaryotic. Doing it at the contig level gives you more information with which to predict whether a sequence is eukaryotic/prokaryotic/viral (since the contig will be longer than the genes found on it). Once you have that list of genes, you can remove them from the data you pass to gRodon.

**Comment by chenyj8** [comment]
OK. Thank you for the clarification. I thought about using kaiju to find prokaryotic genes (https://github.com/bioinformatics-centre/kaiju). But yes, genes are shorter.
