### ISSUE TITLE
Weighted metagenome mode

### ISSUE THREAD

**Issue by eoliver20** [jlw-ecoevo/gRodon#4]
Hi, I have been using gRodon in the metagenome mode but want to try running the weighted option. But it is unclear to me how the median depth is calculated. I am using Prokka to annotate my metagenome assemblies. Is there a way to use the output from Prokka to calculate the read depth? 

Thanks for your help!

**Comment by jlw-ecoevo** [comment]
Hi!

The read depth can be calculated using any read-mapping software to map the reads back to the genes output by prokka

For example, with the [BWA aligner](https://github.com/lh3/bwa) and using [samtools](http://www.htslib.org/) to convert to bam output:
```
bwa index genes.ffn                                                                        
                          
bwa mem genes.ffn reads.fwd.fastq.gs reads.rev.fastq.gz | samtools view -bS - > mapped_reads.bam 
```

And then you can get a nice summary table listing the average coverage of each gene using [bamcov](https://github.com/fbreitwieser/bamcov):
```
bamcov -H mapped_reads.bam > genes_coverage.tbl
```
