### ISSUE TITLE
The fasta file for metagenome I should choose 

### ISSUE THREAD

**Issue by xuanji2017** [jlw-ecoevo/gRodon#5]
Hi
I am really interested in your R package gRodon. I am checking the potential to use it in metagenomics data. In metagenomic mode, should I use MAGs as genome fasta input? Thanks a lot!

Best,

**Comment by jlw-ecoevo** [comment]
You can use either MAGs or assembled metagenomes - although be sure to read the [doumentation](https://jlw-ecoevo.github.io/gRodon-vignette) as the settings you should use for each and their interpretation are different
